version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/bzon/prometheus-msteams
    steps:  
      - checkout
      - setup_remote_docker
      - run: 
          name: Get dependencies
          command: go get -v -t -d ./...
      - run:
          name: Test
          command: |
            make coverage
            bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - deploy:
          name: Publish deployable branches
          command: |
            export APP_VERSION=1.0.0
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              VERSION=${APP_VERSION}-rc.${CIRCLE_BUILD_NUM}
              docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
              make docker_push VERSION=${VERSION}
              docker tag bzon/prometheus-msteams:${VERSION} bzon/prometheus-msteams:latest
              docker push bzon/prometheus-msteams:latest
            fi
            if [[ $CIRCLE_TAG ]]; then
              docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
              make docker_push VERSION=${CIRCLE_TAG}
            fi